// Overall:
//  doc:  https://javadoc.jenkins-ci.org/jenkins/model/Jenkins.html
//  code: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/model/Jenkins.java
public static final PermissionGroup PERMISSIONS           = Permission.HUDSON_PERMISSIONS;
public static final Permission ADMINISTER                 = Permission.HUDSON_ADMINISTER;
public static final Permission MANAGE                     = new Permission(PERMISSIONS,                     "Manage",                                           Messages._Jenkins_Manage_Description(),                             ADMINISTER,                                                                                                 SystemProperties.getBoolean("jenkins.security.ManagePermission"),           new PermissionScope[]{PermissionScope.JENKINS});
public static final Permission SYSTEM_READ                = new Permission(PERMISSIONS,                     "SystemRead",                                       Messages._Jenkins_SystemRead_Description(),                         ADMINISTER,                                                                                                 SystemProperties.getBoolean("jenkins.security.SystemReadPermission"),       new PermissionScope[]{PermissionScope.JENKINS});
public static final Permission READ                       = new Permission(PERMISSIONS,                     "Read",                                             Messages._Hudson_ReadPermission_Description(),                      Permission.READ,                                                                                                                                                                        PermissionScope.JENKINS);
public static final Permission RUN_SCRIPTS                = new Permission(PERMISSIONS,                     "RunScripts",                                       Messages._Hudson_RunScriptsPermission_Description(),                ADMINISTER,                                                                                                                                                                             PermissionScope.JENKINS);

// Credentials
//  doc:  https://javadoc.jenkins.io/plugin/credentials/com/cloudbees/plugins/credentials/CredentialsProvider.html
//  code: https://github.com/jenkinsci/credentials-plugin/blob/master/src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
public static final PermissionGroup GROUP                 = new PermissionGroup(CredentialsProvider.class,  Messages._CredentialsProvider_PermissionGroupTitle());
public static final Permission USE_OWN                    = new Permission(GROUP,                           "UseOwn",                                           Messages._CredentialsProvider_UseOwnPermissionDescription(),        Boolean.getBoolean("com.cloudbees.plugins.credentials.UseOwnPermission") ? Jenkins.ADMINISTER : Job.BUILD,  Boolean.getBoolean("com.cloudbees.plugins.credentials.UseOwnPermission"),   new PermissionScope[]{PermissionScope.ITEM});
public static final Permission USE_ITEM                   = new Permission(GROUP,                           "UseItem",                                          Messages._CredentialsProvider_UseItemPermissionDescription(),       Job.CONFIGURE,                                                                                              Boolean.getBoolean("com.cloudbees.plugins.credentials.UseItemPermission"),  new PermissionScope[]{PermissionScope.ITEM});
public static final Permission CREATE                     = new Permission(GROUP,                           "Create",                                           Messages._CredentialsProvider_CreatePermissionDescription(),        Permission.CREATE,                                                                                          true,                                                                       SCOPES);
public static final Permission UPDATE                     = new Permission(GROUP,                           "Update",                                           Messages._CredentialsProvider_UpdatePermissionDescription(),        Permission.UPDATE,                                                                                          true,                                                                       SCOPES);
public static final Permission VIEW                       = new Permission(GROUP,                           "View",                                             Messages._CredentialsProvider_ViewPermissionDescription(),          Permission.READ,                                                                                            true,                                                                       SCOPES);
public static final Permission DELETE                     = new Permission(GROUP,                           "Delete",                                           Messages._CredentialsProvider_DeletePermissionDescription(),        Permission.DELETE,                                                                                          true,                                                                       SCOPES);
public static final Permission MANAGE_DOMAINS             = new Permission(GROUP,                           "ManageDomains",                                    Messages._CredentialsProvider_ManageDomainsPermissionDescription(), Permission.CONFIGURE,                                                                                       true,                                                                       SCOPES);

// Agent:
//  doc:  https://javadoc.jenkins-ci.org/hudson/model/Computer.html
//  code: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Computer.java
public static final PermissionGroup PERMISSIONS           = new PermissionGroup(Computer.class,             Messages._Computer_Permissions_Title());
public static final Permission CONFIGURE                  = new Permission(PERMISSIONS,                     "Configure",                                        Messages._Computer_ConfigurePermission_Description(),               Permission.CONFIGURE,                                                                                                                                                                   PermissionScope.COMPUTER);
public static final Permission EXTENDED_READ              = new Permission(PERMISSIONS,                     "ExtendedRead",                                     Messages._Computer_ExtendedReadPermission_Description(),            CONFIGURE,                                                                                                  SystemProperties.getBoolean("hudson.security.ExtendedReadPermission"),      new PermissionScope[] {PermissionScope.COMPUTER});
public static final Permission DELETE                     = new Permission(PERMISSIONS,                     "Delete",                                           Messages._Computer_DeletePermission_Description(),                  Permission.DELETE,                                                                                                                                                                      PermissionScope.COMPUTER);
public static final Permission CREATE                     = new Permission(PERMISSIONS,                     "Create",                                           Messages._Computer_CreatePermission_Description(),                  Permission.CREATE,                                                                                                                                                                      PermissionScope.JENKINS);
public static final Permission DISCONNECT                 = new Permission(PERMISSIONS,                     "Disconnect",                                       Messages._Computer_DisconnectPermission_Description(),              Jenkins.ADMINISTER,                                                                                                                                                                     PermissionScope.COMPUTER);
public static final Permission CONNECT                    = new Permission(PERMISSIONS,                     "Connect",                                          Messages._Computer_ConnectPermission_Description(),                 DISCONNECT,                                                                                                                                                                             PermissionScope.COMPUTER);
public static final Permission BUILD                      = new Permission(PERMISSIONS,                     "Build",                                            Messages._Computer_BuildPermission_Description(),                   Permission.WRITE,                                                                                                                                                                       PermissionScope.COMPUTER);

// Job:
//  doc:  https://javadoc.jenkins.io/hudson/model/Item.html
//  code: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Item.java
PermissionGroup PERMISSIONS                               = new PermissionGroup(Item.class,                 Messages._Item_Permissions_Title());
Permission CREATE                                         = new Permission(PERMISSIONS,                     "Create",                                           Messages._Item_CREATE_description(),                                Permission.CREATE,                                                                                                                                                                      PermissionScope.ITEM_GROUP);
Permission DELETE                                         = new Permission(PERMISSIONS,                     "Delete",                                           Messages._Item_DELETE_description(),                                Permission.DELETE,                                                                                                                                                                      PermissionScope.ITEM);
Permission CONFIGURE                                      = new Permission(PERMISSIONS,                     "Configure",                                        Messages._Item_CONFIGURE_description(),                             Permission.CONFIGURE,                                                                                                                                                                   PermissionScope.ITEM);
Permission READ                                           = new Permission(PERMISSIONS,                     "Read",                                             Messages._Item_READ_description(),                                  Permission.READ,                                                                                                                                                                        PermissionScope.ITEM);
Permission DISCOVER                                       = new Permission(PERMISSIONS,                     "Discover",                                         Messages._AbstractProject_DiscoverPermission_Description(),         READ,                                                                                                                                                                                   PermissionScope.ITEM);
Permission EXTENDED_READ                                  = new Permission(PERMISSIONS,                     "ExtendedRead",                                     Messages._AbstractProject_ExtendedReadPermission_Description(),     CONFIGURE,                                                                                                  SystemProperties.getBoolean("hudson.security.ExtendedReadPermission"),      new PermissionScope[] {PermissionScope.ITEM});
Permission BUILD                                          = new Permission(PERMISSIONS,                     "Build",                                            Messages._AbstractProject_BuildPermission_Description(),            Permission.UPDATE,                                                                                                                                                                      PermissionScope.ITEM);
Permission WORKSPACE                                      = new Permission(PERMISSIONS,                     "Workspace",                                        Messages._AbstractProject_WorkspacePermission_Description(),        Permission.READ,                                                                                                                                                                        PermissionScope.ITEM);
Permission WIPEOUT                                        = new Permission(PERMISSIONS,                     "WipeOut",                                          Messages._AbstractProject_WipeOutPermission_Description(),          null,                                                                                                       Functions.isWipeOutPermissionEnabled(),                                     new PermissionScope[] {PermissionScope.ITEM});
Permission CANCEL                                         = new Permission(PERMISSIONS,                     "Cancel",                                           Messages._AbstractProject_CancelPermission_Description(),           Permission.UPDATE,                                                                                                                                                                      PermissionScope.ITEM);
// https://github.com/jenkinsci/cloudbees-folder-plugin/blob/cloudbees-folder-6.10.1/src/main/java/com/cloudbees/hudson/plugins/folder/relocate/RelocationAction.java#L56
Permission RELOCATE                                       = new Permission(Item.PERMISSIONS,                "Move",                                             Messages._RelocateAction_permission_desc(),                         Permission.CREATE,                                                                                                                                                                      PermissionScope.ITEM);

// Run:
//  doc:  https://javadoc.jenkins-ci.org/hudson/model/Run.html
//  code: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Run.java
public static final PermissionGroup PERMISSIONS           = new PermissionGroup(Run.class,                  Messages._Run_Permissions_Title());
public static final Permission DELETE                     = new Permission(PERMISSIONS,                     "Delete",                                           Messages._Run_DeletePermission_Description(),                       Permission.DELETE,                                                                                                                                                                      PermissionScope.RUN);
public static final Permission UPDATE                     = new Permission(PERMISSIONS,                     "Update",                                           Messages._Run_UpdatePermission_Description(),                       Permission.UPDATE,                                                                                                                                                                      PermissionScope.RUN);
public static final Permission ARTIFACTS                  = new Permission(PERMISSIONS,                     "Artifacts",                                        Messages._Run_ArtifactsPermission_Description(),                    null,                                                                                                       Functions.isArtifactsPermissionEnabled(),                                   new PermissionScope[]{PermissionScope.RUN});
// https://github.com/jenkinsci/workflow-cps-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction.java
public static final Permission REPLAY                     = new Permission(Run.PERMISSIONS,                 "Replay",                                           Messages._Replay_permission_description(),                          Item.CONFIGURE,                                                                                                                                                                         PermissionScope.RUN);

// View:
//  doc:  https://javadoc.jenkins.io/hudson/model/View.html
//  code: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/View.java
public static final PermissionGroup PERMISSIONS           = new PermissionGroup(View.class,                 Messages._View_Permissions_Title());
public static final Permission CREATE                     = new Permission(PERMISSIONS,                     "Create",                                           Messages._View_CreatePermission_Description(),                      Permission.CREATE,                                                                                                                                                                      PermissionScope.ITEM_GROUP);
public static final Permission DELETE                     = new Permission(PERMISSIONS,                     "Delete",                                           Messages._View_DeletePermission_Description(),                      Permission.DELETE,                                                                                                                                                                      PermissionScope.ITEM_GROUP);
public static final Permission CONFIGURE                  = new Permission(PERMISSIONS,                     "Configure",                                        Messages._View_ConfigurePermission_Description(),                   Permission.CONFIGURE,                                                                                                                                                                   PermissionScope.ITEM_GROUP);
public static final Permission READ                       = new Permission(PERMISSIONS,                     "Read",                                             Messages._View_ReadPermission_Description(),                        Permission.READ,                                                                                                                                                                        PermissionScope.ITEM_GROUP);

// Job Config History:
//  doc:  https://javadoc.jenkins.io/plugin/jobConfigHistory/hudson/plugins/jobConfigHistory/JobConfigHistory.html
//  code: https://github.com/jenkinsci/job-config-history-plugin/blob/master/src/main/java/hudson/plugins/jobConfigHistory/JobConfigHistory.java
private static final PermissionGroup PERMISSION_GROUP     = new PermissionGroup(JobConfigHistory.class,     Messages._displayName());
protected static final Permission DELETEENTRY_PERMISSION  = new Permission(PERMISSION_GROUP,                Messages.JobConfigHistory_deleteEntryPermission(),  Messages._JobConfigHistory_deleteEntryPermissionDescription(),      Jenkins.ADMINISTER,                                                                                         true,                                                                       new PermissionScope[]{PermissionScope.ITEM, PermissionScope.COMPUTER});

// SCM:
//  doc:  https://javadoc.jenkins-ci.org/hudson/scm/SCM.html
//  code: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/scm/SCM.java
public static final PermissionGroup PERMISSIONS           = new PermissionGroup(SCM.class,                  Messages._SCM_Permissions_Title());
public static final Permission TAG                        = new Permission(PERMISSIONS,                     "Tag",                                              Messages._SCM_TagPermission_Description(),                          Permission.CREATE,                                                                                                                                                                      PermissionScope.ITEM);

// N/A
//  doc:  https://javadoc.jenkins.io/hudson/security/Permission.html
//  code: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/security/Permission.java
// hudson.security.Permission.FULL_CONTROL
public static final PermissionGroup HUDSON_PERMISSIONS    = new PermissionGroup(Hudson.class,               hudson.model.Messages._Hudson_Permissions_Title());
public static final PermissionGroup GROUP                 = new PermissionGroup(Permission.class,           Messages._Permission_Permissions_Title());
public static final Permission HUDSON_ADMINISTER          = new Permission(HUDSON_PERMISSIONS,              "Administer",                                       hudson.model.Messages._Hudson_AdministerPermission_Description(),   null);
public static final Permission FULL_CONTROL               = new Permission(GROUP,                           "FullControl",                                      null,                                                               HUDSON_ADMINISTER);
public static final Permission READ                       = new Permission(GROUP,                           "GenericRead",                                      null,                                                               HUDSON_ADMINISTER);
public static final Permission WRITE                      = new Permission(GROUP,                           "GenericWrite",                                     null,                                                               HUDSON_ADMINISTER);
public static final Permission CREATE                     = new Permission(GROUP,                           "GenericCreate",                                    null,                                                               WRITE);
public static final Permission UPDATE                     = new Permission(GROUP,                           "GenericUpdate",                                    null,                                                               WRITE);
public static final Permission DELETE                     = new Permission(GROUP,                           "GenericDelete",                                    null,                                                               WRITE);
public static final Permission CONFIGURE                  = new Permission(GROUP,                           "GenericConfigure",                                 null,                                                               UPDATE);
